# Generated by Django 3.2.16 on 2022-11-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20221128_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcuto',
            new_name='Producto',
        ),
    ]
