# Generated by Django 3.2.16 on 2022-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
